// DO NOT EDIT THIS FILE AS IT IS GENERATED BY @r2d2bzh/js-backend-rules
library 'shared-libraries@master'
buildOctoHecker {
    serviceName = "gateway.rel pizza.rel"
    releaseName = "moleculer_test"
    customBuildSteps = "docker-compose build share"
    testCommand = "docker-compose run test"
    testTeardown = "docker-compose down"
    sonarCheck = true
}
